# Columns Transformation

In [32]:
import pandas as pd
df = pd.read_csv("customer.csv")
data

,id,firstname,lastname,email,email2,profession
0,100,Laurene,Tamar,Laurene.Tamar@yopmail.com,Laurene.Tamar@gmail.com,NaN
1,101,Sara-Ann,Oster,Sara-Ann.Oster@yopmail.com,NaN,doctor
2,102,Dulcinea,Sikorski,Dulcinea.Sikorski@yopmail.com,Dulcinea.Sikorski@gmail.com,doctor
3,103,Candy,Geffner,Candy.Geffner@yopmail.com,Candy.Geffner@gmail.com,worker
4,104,Arlina,Hamil,Arlina.Hamil@yopmail.com,Arlina.Hamil@gmail.com,developer
...,...,...,...,...,...,...
996,1096,Cassondra,Shanley,Cassondra.Shanley@yopmail.com,Cassondra.Shanley@gmail.com,worker
997,1097,Wanda,Kress,Wanda.Kress@yopmail.com,Wanda.Kress@gmail.com,police officer
998,1098,Shaylyn,Urias,Shaylyn.Urias@yopmail.com,Shaylyn.Urias@gmail.com,firefighter
999,1099,Kirstin,Gualtiero,Kirstin.Gualtiero@yopmail.com,Kirstin.Gualtiero@gmail.com,police officer
1000,1099,Kirstin,Gualtiero,Kirstin.Gualtiero@yopmail.com,Kirstin.Gualtiero@gmail.com,police officer

In [33]:
df.loc[(df["Bonus"]==0),"GetBonus"] = "No Bonus"
df.loc[(df["Bonus"]>0),"GetBonus"] = "Bonus"
df.head(10) #Show me the details who gets bounus and who not

,id,firstname,lastname,email,email2,profession,Bonus,GetBonus
0,100,Laurene,Tamar,Laurene.Tamar@yopmail.com,Laurene.Tamar@gmail.com,NaN,NaN,nan
1,101,Sara-Ann,Oster,Sara-Ann.Oster@yopmail.com,NaN,doctor,100000.0,Bonus
2,102,Dulcinea,Sikorski,Dulcinea.Sikorski@yopmail.com,Dulcinea.Sikorski@gmail.com,doctor,100000.0,Bonus
3,103,Candy,Geffner,Candy.Geffner@yopmail.com,Candy.Geffner@gmail.com,worker,100000.0,Bonus
4,104,Arlina,Hamil,Arlina.Hamil@yopmail.com,Arlina.Hamil@gmail.com,developer,100000.0,Bonus
5,105,Noelle,Suzetta,Noelle.Suzetta@yopmail.com,Noelle.Suzetta@gmail.com,firefighter,NaN,nan
6,106,Therine,Marcellus,Therine.Marcellus@yopmail.com,Therine.Marcellus@gmail.com,firefighter,NaN,nan
7,107,Madeleine,Read,Madeleine.Read@yopmail.com,Madeleine.Read@gmail.com,doctor,NaN,nan
8,108,Leia,Alfons,Leia.Alfons@yopmail.com,Leia.Alfons@gmail.com,developer,100000.0,Bonus
9,109,Ekaterina,Ludewig,Ekaterina.Ludewig@yopmail.com,Ekaterina.Ludewig@gmail.com,doctor,100000.0,Bonus

In [34]:
data["fullname"] = data["firstname"] +" "+ data["lastname"]
data #Create a new columns and the full name is shown

,id,firstname,lastname,email,email2,profession,fullname
0,100,Laurene,Tamar,Laurene.Tamar@yopmail.com,Laurene.Tamar@gmail.com,NaN,Laurene Tamar
1,101,Sara-Ann,Oster,Sara-Ann.Oster@yopmail.com,NaN,doctor,Sara-Ann Oster
2,102,Dulcinea,Sikorski,Dulcinea.Sikorski@yopmail.com,Dulcinea.Sikorski@gmail.com,doctor,Dulcinea Sikorski
3,103,Candy,Geffner,Candy.Geffner@yopmail.com,Candy.Geffner@gmail.com,worker,Candy Geffner
4,104,Arlina,Hamil,Arlina.Hamil@yopmail.com,Arlina.Hamil@gmail.com,developer,Arlina Hamil
...,...,...,...,...,...,...,...
996,1096,Cassondra,Shanley,Cassondra.Shanley@yopmail.com,Cassondra.Shanley@gmail.com,worker,Cassondra Shanley
997,1097,Wanda,Kress,Wanda.Kress@yopmail.com,Wanda.Kress@gmail.com,police officer,Wanda Kress
998,1098,Shaylyn,Urias,Shaylyn.Urias@yopmail.com,Shaylyn.Urias@gmail.com,firefighter,Shaylyn Urias
999,1099,Kirstin,Gualtiero,Kirstin.Gualtiero@yopmail.com,Kirstin.Gualtiero@gmail.com,police officer,Kirstin Gualtiero
1000,1099,Kirstin,Gualtiero,Kirstin.Gualtiero@yopmail.com,Kirstin.Gualtiero@gmail.com,police officer,Kirstin Gualtiero

In [38]:
data = {"Months": ["January", "February", "March", "April"]}
a = pd.DataFrame(data)  

def extract(value):
    return value[0:3]  

a["Short Month"] = a["Months"].map(extract)  
print(a)

     Months Short Month
0   January         Jan
1  February         Feb
2     March         Mar
3     April         Apr